steps:
  # downloading artifact
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: 'Download build artifacts'

  # installing dependencies
  - script: |
      python --version
      python -m ensurepip --upgrade
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Unit tests
  - script: |
      mkdir -p junit
      python -m pytest test_hello_world.py --junitxml=junit/test-results.xml
    displayName: 'Run unit tests'

  # integration tests
  - script: |
      python hello_world.py &
      echo $! > flask.pid
      sleep 5
      python -m pytest test_integration.py --junitxml=junit/integration-test-results.xml
      kill -9 $(cat flask.pid)
    displayName: 'Run integration tests'

  - task: PublishTestResults@2
    inputs:
      testRunFormat: 'JUnit'
      testResultsFiles: '**/junit/*.xml'
      testRunTitle: 'Python Tests'
    condition: succeededOrFailed()

  # - task: Docker@2
  #   displayName: Build and push Docker image to Nexus
  #   inputs:
  #     containerRegistry: 'NexusRM PRD-DevOpsReference' 
  #     repository: 'ema/devopstest'
  #     command: 'buildAndPush'
  #     Dockerfile: '**/Dockerfile'
  #     tags: |
  #       $(Build.BuildId)
  #       latest


  - task: Bash@3
    name: TestImagetoNexus
    displayName: creates and uploads docker image to Nexus
    inputs:
      targetType: 'inline'
      script: |
        export http_proxy='http://proxy.eudra.org:8080'
        export https_proxy='http://proxy.eudra.org:8080'
        export no_proxy='localhost,127.0.0.1,.emea.eu.int,.ema.europa.eu,.eudra.org'
        echo "building docker image"
        docker build -t devopstest .
        echo "Image built ema/devopstest"
        docker tag ema/devopstest registry.ema.europa.eu/ema/devopstest
        echo "Image tagged for registry ema/devopstest"
        docker push localhost/devopstest registry.ema.europa.eu/ema/devopstest
        echo "Image pushed to registry ema/devopstest"

