parameters:
  pythonVersion: '3.x'

steps:
  - script: |
      python --version
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
