parameters:
  pythonVersion: '3.x'

steps:
  # installing dependencies
  - script: |
      python --version
      python -m ensurepip --upgrade
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  # copying artifacts to directory
  - task: CopyFiles@2
    inputs:
      contents: |
        **/*.py
        requirements.txt
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy files to artifact directory'

  # publishing artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publish artifact'
