parameters: 
  pythonVersion: '3.x'

steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'dev-devopsreference-00001-spn'
      appName: 'Azure-pipeline-test'
      package: '$(System.DefaultWorkingDirectory)'
      startUpCommand: python hello_world.py