parameters: 
  pythonVersion: '3.9'

steps:
  # downloading artifacts
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.ArtifactsDirectory)' 
      includedRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactsStagingDirectory)/app.zip'
      replaceExistingArchive: true

  # creating virtual machine resources
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'dev-devopsreference-00001-spn'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |

        # Create storage container
        az storage account create --name devdevopsref00001sa --resource-group dev-devopsreference-00001-rg --location centraleu --sku Standard_LRS
        az storage container create --name artifacts --account-name dev-devopsreference-00001-rg --auth-mode login

        az vm create --resource-group dev-devopsreference-00001-rg --name dev-devopsreference-00001-vm --image Ubuntu2204 --admin-username azureuser --generate-ssh-keys
        
        

        az vm run-command invoke --resource-group dev-devopsreference-00001-rg --name dev-devopsreference-00001-vm --command-id RunShellScript --scripts "chmod +x /home/azureuser/startup_script.sh && /home/azureuser/startup_script.sh"
