version: 0.2

phases:

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws --version
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - mkdir -p ~/.docker
      - echo '{"proxies":{"default":{"httpProxy":"'$HTTP_PROXY'","httpsProxy":"'$HTTPS_PROXY'","noProxy":"'$NO_PROXY'"}}}' > ~/.docker/config.json
      - cat ~/.docker/config.json
      - export NO_PROXY="$NO_PROXY,public.ecr.aws"

  build:
    commands:
      - echo "Building docker image"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing docker image"
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"ecs-test", "imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
  - imagedefinitions.json
  - '**/*'
  discard-paths: yes
  base-directory: '.'

