version: 0.2

phases:

  # The image needs to be created locally, fetching it from anywhere is too much of a hassle

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws --version
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}
      - docker commit $(hostname) codebuild:local

  build:
    commands:
      - echo "Building docker image"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing docker image"
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"ecs-test", "imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
  - imagedefinitions.json
  - '**/*'
  discard-paths: yes
  base-directory: '.'

